# Generated by Django 3.1.3 on 2022-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gradenum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
