# Generated by Django 3.1.3 on 2022-08-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(0, '教室ほうき'), (1, '教室机寄せ'), (2, '教室モップ'), (3, '黒板'), (4, '理科室'), (5, '男子トイレ'), (6, '女子トイレ'), (7, '美化委員の仕事')])),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLunchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABC', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
    ]
