# Generated by Django 3.1.3 on 2022-08-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20220825_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDutyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=7)),
                ('tuesday', models.CharField(max_length=7)),
                ('wednesday', models.CharField(max_length=7)),
                ('thursday', models.CharField(max_length=7)),
                ('friday', models.CharField(max_length=7)),
            ],
        ),
    ]
