# Generated by Django 3.1.3 on 2022-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_daydutymodel_schedulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='classnum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='gradenum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
