# Generated by Django 3.1.3 on 2022-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20220830_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydutymodel',
            name='classnum',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='daydutymodel',
            name='gradenum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
