# Generated by Django 3.1.3 on 2022-12-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='category',
            field=models.IntegerField(choices=[(0, 'お知らせ'), (1, '重要')], default=0),
            preserve_default=False,
        ),
    ]
